#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 5.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

# scripts that run after cloning repository
install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: '{version}-prerelease'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:

  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages

# MSBuild verbosity level
  verbosity: quiet|minimal|normal|detailed

# to run your custom scripts instead of automatic MSBuild
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  nuget pack src\NHibernate.JetDriver\NHibernate.JetDriver.csproj -Version $env:appveyor_build_version -Verbosity detailed

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests against only selected assemblies and/or categories
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

# artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  # - path: src/NHibernate.JetDriver/bin/$(configuration)
  #  name: NHibernate.JetDriver.dll

  # pushing all *.nupkg files in build directory recursively
  # - path: '**\*.nupkg'
  # path: src/NHibernate.JetDriver/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#



#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - christian.junk@geomatics.io
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false