version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_informational_version: '5.1.0.0-b{build}'
test: off
artifacts:
- path: artifacts\**\*.nupkg
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true 
deploy:
  provider: NuGet
  api_key:
    secure: AlZb9RmiC8ciqIT8+BygQoiae07DdHKte0lnn8ZQgHgj25ZBi6hXLIe4UPeNJwnQ
  skip_symbols: false
  artifact: /.*\.nupkg/
notifications:
- provider: Email
  to:
  - christian.junk@geomatics.io
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false